import { store } from '../main.js';
import { embed } from '../util.js';
import { score } from '../score.js';
import { fetchEditors, fetchList } from '../content.js';

import Spinner from '../components/Spinner.js';
import LevelAuthors from '../components/List/LevelAuthors.js';

const roleIconMap = {
	owner: 'crown',
	admin: 'user-gear',
	helper: 'user-shield',
	dev: 'code',
	trial: 'user-lock',
};

export default {
	components: { Spinner, LevelAuthors },
	template: `
        <main v-if="loading" class="surface">
            <Spinner></Spinner>
        </main>
        <main v-else class="page-list">
                </div>
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
                uptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntotheflooruptotheceilingdowntothefloor
            </div>
        </main>
    `,
	data: () => ({
		list: [],
		editors: [],
		loading: true,
		selected: 0,
		errors: [],
		roleIconMap,
		store,
		toggledShowcase: false,
	}),
	computed: {
		level() {
			return this.list[this.selected][0];
		},
		video() {
			if (!this.level.showcase) {
				return embed(this.level.verification);
			}

			return embed(
				this.toggledShowcase ? this.level.showcase : this.level.verification,
			);
		},
	},
	async mounted() {
		// Hide loading spinner
		this.list = await fetchList();
		this.editors = await fetchEditors();

		// Error handling
		if (!this.list) {
			this.errors = [
				'Failed to load list. Retry in a few minutes or notify list staff.',
			];
		} else {
			this.errors.push(
				...this.list
					.filter(([_, err]) => err)
					.map(([_, err]) => {
						return `Failed to load level. (${err}.json)`;
					}),
			);
			if (!this.editors) {
				this.errors.push('Failed to load list editors.');
			}
		}

		this.loading = false;
	},
	methods: {
		embed,
		score,
	},
};
